# launcher name & url
launcher_name=NovaLauncher
launcher_app_name=Nova Launcher
launcher_short_name=NL2
url_home=https://github.com/shubhamvalacha14-ctrl/Nova-Launcher

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
#curseforge_api_key=xxx

# default key, please add it yourself.
default_store_password=vh#mn$N(#ekjwfA7B-77s&F-cdd(@-7eana-%!nhj%))!@c
default_key_password=sfv72ghSSNQaadF99-Q6912

# launcher version
launcher_version_code=200025
launcher_version_name=2.4.3
